### ISSUE TITLE
php client

### ISSUE THREAD

**Issue by dimst** [Doncode/simple_php_websocket_server#2]
Здравствуйте.  Хочу реализовать цепочку:
клиент.php <==> demon.php <==> браузер

'demon.php' и 'браузер'  - полет отличный, 'клиент.php' и 'demon.php'  - так же
Но 'браузер' не видит сообщения от 'клиент.php'. Что можно сделать?

**Comment by Doncode** [comment]
Привет. 

Как понял что 'клиент.php' и 'demon.php'  все ок.
Что в  'клиент.php' 

Пятница, 13 декабря 2013, 13:09 -08:00 от DiM notifications@github.com:

> Здравствуйте.  Хочу реализовать цепочку:
> клиент.php <==> demon.php <==> браузер
> 'demon.php' и 'браузер'  - полет отличный, 'клиент.php' и 'demon.php'  - так же
> Но 'браузер' не видит сообщения от 'клиент.php'. Что можно сделать?
> —
> Reply to this email directly or  view it on GitHub .

## 

Саня -

**Comment by coffebar** [comment]
Ты написал что хочешь реализовать цепочку 
клиент.php <==> demon.php <==> браузер

т.е. Клиент -> Сервер -> Другой клиент

так в чем проблема? тебе не нужна прямая связь между клиентами, их должен объединять сервер, т.е demon.php и пересылать сообщения всем клиентам
